name: application-status-classifier
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.0
  - pandas
  - numpy=1.26.4
  - nltk
  - pip
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - transformers
  - pytorch
  - tensorflow
  # - typing-extensions=4.8.0
  # - pydantic=2.8.2
  # - spacy=3.8.2
  # - thinc=8.0.15
  # - torch=2.3.1
  - pip:
    - -r requirements.txt